import test from "node:test";
import assert from "node:assert/strict";
import { analyzeContinuity, compilePrompt, findPreviousShot, resolveDurationSeconds, sceneIdForShot, type ProductionProject } from "../lib/production.ts";
import { analyzeShotWithFallback } from "../lib/shot-analysis.ts";
import { buildGenerationPackageV1, buildGenerationPreflight, validateGenerationPackage, VIBES_PROJECT_URL } from "../lib/generation-package.ts";
import { resolveGenerationAssets } from "../lib/browser-bridge-client.ts";
import { validateBridgeCommand } from "../browser-extension/shared/generation-package-v1.js";
const appOrigin="https://property-director-studio.iagomaneiraso.chatgpt.site";

function fixture(): ProductionProject {
  const project: ProductionProject = {
    title:"SCAEVA",url:"",style:"cinematic",styleNegative:"no text",budgetMode:"BALANCED",storyRules:"Preserve chronology",continuityRules:"Approved frames are canonical",props:[],
    characters:[
      {id:"scaeva",name:"Scaeva",role:"hero",activeVersionId:"scaeva-v1",versions:[{id:"scaeva-v1",label:"V1",active:true,promptAnchor:"Roman boy",immutable:"same face",forbidden:"identity drift",references:[{id:"scaeva-official",name:"Scaeva Official.png",type:"image/png",kind:"OFFICIAL_IDENTITY"}]}]},
      {id:"vitus",name:"Vitus",role:"support",activeVersionId:"vitus-v1",versions:[{id:"vitus-v1",label:"V1",active:true,promptAnchor:"ginger Roman teen",immutable:"long hair",forbidden:"short hair",references:[{id:"vitus-official",name:"Vitus Official.png",type:"image/png",kind:"OFFICIAL_IDENTITY"},{id:"vitus-hair",name:"Vitus Hair Reference.png",type:"image/png",kind:"HAIR"}]}]},
    ],
    locations:[{id:"alley",name:"Roman Alley",versions:[{id:"alley-v1",label:"V1",promptAnchor:"stone alley",immutable:"same door",forbidden:"modern objects",references:[{id:"alley-ref",name:"Roman Alley.png",type:"image/png"}]}]}],
    scenes:[
      {id:"shot-04-06",title:"Running",sceneNumber:4,shotNumber:6,action:"Scaeva runs",camera:"wide",duration:"4",durationMode:"MANUAL",continuity:"same alley",negative:"text",assets:[],queued:false,status:"APPROVED",qualityTarget:"STANDARD",preferredProvider:"vibes",startFrameMode:"CANONICAL",characterVersionIds:["scaeva-v1"],locationVersionId:"alley-v1",transitionType:"AUTO",autoMode:true,approvedTakeId:"take-06",takes:[{id:"take-06",provider:"vibes",model:"",status:"APPROVED",prompt:"p",createdAt:"2026-01-01T00:00:00Z",rejectionReasons:[],notes:"",finalFrame:{id:"frame-06",name:"04.06 Last Frame.png",type:"image/png"}}]},
      {id:"shot-04-07",title:"The Hand",sceneNumber:4,shotNumber:7,action:"Vitus aparece no beco com o cabelo ruivo comprido, ajuda Scaeva e a ação continua pela rota de fuga",camera:"tracking",duration:"AUTO",durationMode:"AUTO",continuity:"continuous action",negative:"morph",storyboard:{id:"board-07",name:"04.07 Storyboard.png",type:"image/png",kind:"STORYBOARD"},assets:[],queued:false,status:"READY",qualityTarget:"STANDARD",preferredProvider:"vibes",startFrameMode:"PREVIOUS_LAST_FRAME",characterVersionIds:["scaeva-v1","vitus-v1"],locationVersionId:"",transitionType:"AUTO",autoMode:true,takes:[]},
    ],
  };
  const shot=project.scenes[1];shot.analysis=analyzeContinuity(project,shot.id);shot.preparedPrompt=compilePrompt(project,shot,"vibes",shot.analysis);return project;
}

test("AI analysis success uses the AI result", async()=>{const project=fixture();const result=await analyzeShotWithFallback(project,"shot-04-07",async(local)=>({analysis:{...local.analysis,score:97},prompt:"AI prompt",provider:"openai",model:"test-model"}));assert.equal(result.usedFallback,false);assert.equal(result.provider,"openai");assert.equal(result.prompt,"AI prompt");assert.equal(result.analysis.score,97);});
test("AI analysis failure prepares the shot with deterministic local analysis",async()=>{const result=await analyzeShotWithFallback(fixture(),"shot-04-07",async()=>{throw new Error("provider unavailable");});assert.equal(result.usedFallback,true);assert.equal(result.warningCode,"AI_ANALYSIS_UNAVAILABLE");assert.match(result.warning||"",/análise local/i);assert.ok(result.prompt);});
test("04.07 resolves 04.06 by scene and shot number",()=>{const project=fixture();const result=findPreviousShot(project,sceneIdForShot(project.scenes[1]),"shot-04-07");assert.equal(result.expectedCode,"04.06");assert.equal(result.shot?.id,"shot-04-06");assert.equal(result.approvedFrame?.id,"frame-06");});
test("04.07 package without location but with storyboard is valid",()=>{const project=fixture();project.scenes=[project.scenes[1]];const shot=project.scenes[0];shot.analysis=analyzeContinuity(project,shot.id);shot.preparedPrompt=compilePrompt(project,shot,"vibes",shot.analysis);const previous=findPreviousShot(project,sceneIdForShot(shot),shot.id);const value=buildGenerationPackageV1(project,shot,appOrigin,"request-missing-06");const preflight=buildGenerationPreflight(project,shot,value);assert.equal(previous.expectedCode,"04.06");assert.equal(previous.shot,undefined);assert.equal(preflight.valid,true);assert.equal(preflight.ready,true);assert.equal(preflight.environmentSource,"storyboard");assert.deepEqual(preflight.missing,[]);assert.deepEqual(preflight.invalid,[]);assert.deepEqual(preflight.unresolvedAssets,[]);assert.deepEqual(preflight.warnings,["Previous shot 04.06 is not imported.","Location not explicitly assigned; storyboard will be used as environment reference."]);});
test("04.07 bridge package is limited to four references and five seconds",()=>{const shot=fixture().scenes[1];const value=buildGenerationPackageV1(fixture(),shot,appOrigin,"request-minimal");assert.equal(value.generation.durationSeconds,5);assert.equal(value.generation.aspectRatio,"16:9");assert.equal(value.references.length,4);assert.deepEqual(value.references.map((item)=>item.role),["STORYBOARD","CHARACTER_OFFICIAL_IDENTITY","CHARACTER_OFFICIAL_IDENTITY","CHARACTER_HAIR"]);});
test("missing Vibes project URL has a field error",()=>{const project=fixture();const value=buildGenerationPackageV1(project,project.scenes[1],appOrigin,"request-1","");const result=validateGenerationPackage(value);assert.equal(result.success,false);assert.ok(result.errors.missing.some((item)=>item.code==="MISSING_PROJECT_URL"));});
test("unresolved asset reports its name",async()=>{const project=fixture();const value=buildGenerationPackageV1(project,project.scenes[1],appOrigin,"request-2",VIBES_PROJECT_URL);await assert.rejects(()=>resolveGenerationAssets(value,async()=>{throw new Error("offline");}),/04\.07 Storyboard\.png could not be resolved\./);});
test("valid GenerationPackageV1 passes the shared validator",()=>{const project=fixture();const value=buildGenerationPackageV1(project,project.scenes[1],appOrigin,"request-3");assert.equal(value.schemaVersion,1);assert.equal(typeof value.generation.durationSeconds,"number");assert.equal(validateGenerationPackage(value).success,true);});
test("invalid package returns missing and invalid field details",()=>{const result=validateGenerationPackage({schemaVersion:1,requestId:"r",project:{id:"main",videoProvider:"vibes",vibesProjectUrl:""},shot:{},generation:{durationSeconds:"AUTO"},references:[]});assert.ok(result.errors.missing.some((item)=>item.path==="project.vibesProjectUrl"));assert.ok(result.errors.invalid.some((item)=>item.code==="INVALID_DURATION"));});
test("Bridge accepts a valid package",()=>{const project=fixture();const value=buildGenerationPackageV1(project,project.scenes[1],appOrigin,"request-4");assert.equal(validateBridgeCommand({version:1,type:"PD_START_GENERATION",generationPackage:value}).accepted,true);});
test("Bridge rejects a malformed package with details",()=>{const result=validateBridgeCommand({version:1,type:"PD_START_GENERATION",generationPackage:{schemaVersion:1}});assert.equal(result.accepted,false);assert.equal(result.stage,"PACKAGE_VALIDATION");assert.ok(result.details&&result.details.missing.length>0);});
